name: "analytics"
version: "1.0.0"
config-version: 2

profile: "analytics"
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +post-hook:
    - "{{ dagster.log_columns_in_relation() }}"

  analytics:
    staging:
      +schema: staging
      +materialized: view
      postgres:
        +meta:
          dagster:
            group: cloud_staging
      telemetry:
        +meta:
          dagster:
            group: oss_telemetry_staging
      salesforce:
        +meta:
          dagster:
            group: salesforce_staging
      stripe:
        +meta:
          dagster:
            group: stripe_staging
      segment:
        +meta:
          dagster:
            group: segment_staging
      thinkific:
        +meta:
          dagster:
            group: education
      slack:
        +meta:
          dagster:
            group: slack_staging
    intermediate:
      +schema: intermediate
      +materialized: view
      marketing:
        +meta:
          dagster:
            group: marketing_intermediate
      product:
        +meta:
          dagster:
            group: cloud_intermediate
      stripe:
        +meta:
          dagster:
            group: stripe_intermediate
    marts:
      +materialized: table
      telemetry:
        +schema: telemetry
        +meta:
          dagster:
            group: oss_telemetry
      cloud_reporting:
        +schema: cloud_reporting
        +meta:
          dagster:
            group: cloud_reporting
      core:
        +schema: core
        +meta:
          dagster:
            group: cloud_core
      product:
        +schema: product
        +meta:
          dagster:
            group: cloud_product
      marketing:
        +schema: marketing
        +meta:
          dagster:
            group: marketing
      finance:
        +schema: finance
        +meta:
          dagster:
            group: finance
      sales:
        +schema: sales
        +meta:
          dagster:
            group: sales
      hightouch:
        +schema: hightouch
        +meta:
          dagster:
            group: hightouch
      education:
        +schema: education
        +meta:
          dagster:
            group: education

seeds:
  +post-hook:
    - "{{ dagster.log_columns_in_relation() }}"

  +meta:
    dagster:
      group: cloud_staging

vars:
  session_threshold_seconds: 1800
  attribution_lookback_days: 30
  dev_num_days_to_include: 90
  # These variables are used for incremental models
  min_date: "2000-01-01"
  max_date: "9999-12-31"
  stripe_source:
    stripe_database: FIVETRAN
    stripe_schema: STRIPE_PROD
    using_invoices: true
    using_credit_notes: false
    using_payment_method: true
    using_subscriptions: true
    stripe__subscription_history: true
    using_livemode: true
    using_invoice_line_sub_filter: false
  stripe:
    stripe__subscription_history: true
    stripe_database: FIVETRAN
    stripe_schema: STRIPE_PROD
    stripe_timezone: "America/Los_Angeles"

query-comment:
  # must match the python implementation
  comment: "snowflake_dagster_dbt_v1_opaque_id[[[{{ node.unique_id }}:{{ invocation_id }}]]]"
  append: true
