---
name: "purina_dbt"
version: "1.0.0"
config-version: 2

profile: "purina_dbt"
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
    staging:
      postgres:
        +schema: staging
        +materialized: view

tests:
  +meta:
    dagster:
      asset_check: True

vars:
  dev_num_days_to_include: 90
