name: "analytics"
version: "1.0.0"
config-version: 2

profile: "analytics"
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics:
    staging:
      +schema: staging
      +materialized: view
      postgres:
        +meta:
          dagster:
            group: cloud_staging
      telemetry:
        +meta:
          dagster:
            group: oss_telemetry_staging
      salesforce:
        +meta:
          dagster:
            group: salesforce_staging
      stripe:
        +meta:
          dagster:
            group: stripe_staging
    intermediate:
      +schema: intermediate
      +materialized: view
      product:
        +meta:
          dagster:
            group: cloud_intermediate
      stripe:
        +meta:
          dagster:
            group: stripe_intermediate
    marts:
      +materialized: table
      telemetry:
        +schema: telemetry
        +meta:
          dagster:
            group: oss_telemetry
      cloud_reporting:
        +schema: cloud_reporting
        +meta:
          dagster:
            group: cloud_reporting
      core:
        +schema: core
        +meta:
          dagster:
            group: cloud_core
      product:
        +schema: product
        +meta:
          dagster:
            group: cloud_product

seeds:
  +meta:
    dagster:
      group: cloud_staging

tests:
  +meta:
    dagster:
      asset_check: True

vars:
  dev_num_days_to_include: 90