name: "analytics"
version: "1.0.0"
config-version: 2

profile: "analytics"
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics:
    staging:
      +schema: staging
      +materialized: view
      postgres:
        +meta:
          dagster:
            group: cloud_staging
      telemetry:
        +meta:
          dagster:
            group: oss_telemetry_staging
    marts:
      +materialized: table
      telemetry:
        +schema: telemetry
        +meta:
          dagster:
            group: oss_telemetry

tests:
  +meta:
    dagster:
      asset_check: True

vars:
  dev_num_days_to_include: 90
