source: CLOUD_PRODUCTION
target: SLING_DB
defaults: 
  mode: incremental
  object: '{stream_table}'
  primary_key: [id]

streams: 
  public.asset_keys: 
    update_key: last_materialization_timestamp
    meta:
      dagster: 
        asset_key: sling.cloud_product.asset_keys
  
  public.customer_info: 
    meta:
      dagster:
        asset_key: sling.cloud_product.customer_info
  
  public.deployments: 
    meta: 
      dagster: 
        asset_key: sling.cloud_product.deployments
  
  public.onboarding_checklist: 
    primary_key: [entry_key, organization_id]
    update_key: update_timestamp
    meta: 
        dagster:
          asset_key: sling.cloud_product.onboarding_checklist
  
  public.organizations: 
    update_key: update_timestamp
    meta:
      dagster:
        asset_key: sling.cloud_product.organizations
  
  public.permissions: 
    meta:
      dagster:
        asset_key: sling.cloud_product.permissions
  
  public.serverless_agents: 
    update_key: update_timestamp
    meta:
      dagster:
        asset_key: sling.cloud_product.serverless_agents
  
  public.session_tokens: 
    update_key: update_timestamp
    meta:
      dagster:
        asset_key: sling.cloud_product.session_tokens
  
  public.users: 
    meta:
      dagster:
        asset_key: sling.cloud_product.users
  
  public.users_organizations: 
    meta:
      dagster:
        asset_key: sling.cloud_product.users_organizations
  
  public.users_permissions: 
    meta:
      dagster:
        asset_key: sling.cloud_product.users_permissions

  public.teams: 
    update_key: update_timestamp
    meta:
      dagster:
        asset_key: sling.cloud_product.teams
  
  public.teams_users: 
    meta:
      dagster:
        asset_key: sling.cloud_product.teams_users
  
  public.teams_permissions: 
    meta:
      dagster:
        asset_key: sling.cloud_product.teams_permissions
  
  public.repository_locations_data: 
    sql: |
      select
        id, 
        organization_id, 
        deployment_id, 
        create_timestamp, 
        timestamp as update_timestamp,
        jsonb_path_query_array(
          replace(replace(load_repositories_response, ': Infinity', ': 0'), ': NaN', ': 0')::jsonb,
          '$.repository_datas[0].external_repository_data.external_asset_graph_data[*].asset_key'
        ) as asset_keys,
        jsonb_path_query_array(
          replace(replace(load_repositories_response, ': Infinity', ': 0'), ': NaN', ': 0')::jsonb,
          '$.repository_datas[0].external_repository_data.external_asset_graph_data[*].group_name'
        ) as group_names,
        jsonb_path_query(
          replace(replace(load_repositories_response, ': Infinity', ': 0'), ': NaN', ': 0')::jsonb,
          '$.dagster_library_versions'
        ) as dagster_library_versions
      from repository_locations_data
      where timestamp > current_timestamp - interval '1 day'
    meta:
      dagster:
        asset_key: sling.cloud_product.repository_locations_data