source: CLOUD_PRODUCTION_MAIN
target: SLING_DB_MAIN
defaults: 
  mode: incremental
  object: '{stream_table}'
  update_key: id

streams: 
  public.event_logs_view:
    sql: >
      with candidates as (
        select * from public.event_logs_partitioned where id > {incremental_value} and id <= {incremental_value} + 500000
      )
      select * from candidates where dagster_event_type is not null
    meta:
      dagster: 
        asset_key: sling.cloud_product.event_logs
    object: cloud_product.event_logs
