source: CLOUD_PRODUCTION_SHARD1
target: SLING_DB_SHARD1
defaults: 
  mode: incremental
  object: '{stream_table}'

streams: 
  public.event_logs_partitioned:
    primary_key: [date, organization_id]
    sql: >
      select
        date(timestamp) as date,
        organization_id,
        count(*) as user_events_count
      from event_logs_partitioned
      where
        dagster_event_type is null
        and date(timestamp) between current_date - 7
        and current_date
      group by date, organization_id
    meta:
      dagster: 
        asset_key: sling.cloud_product_shard1.user_events_counts
    object: cloud_product_shard1.user_events_counts
