source: CLOUD_PRODUCTION_MAIN
target: SLING_DB_MAIN
defaults: 
  mode: incremental
  object: '{stream_table}'
  update_key: id
  source_options:
    limit: 500000

streams: 
  public.event_logs:
    sql: >
      SELECT * FROM public.event_logs where {incremental_where_cond} and dagster_event_type is not null
    meta:
      dagster: 
        asset_key: sling.cloud_product.event_logs
