source: CLOUD_PRODUCTION_MAIN
target: SLING_DB_MAIN
defaults: 
  mode: incremental
  object: '{stream_table}'
  update_key: id
  source_options:
    limit: 500000

streams:
  public.run_tags: 
    meta:
      dagster:
        asset_key: sling.cloud_product.run_tags
    
  public.asset_materializations:
    update_key: event_id
    meta:
      dagster: 
        asset_key: sling.cloud_product.asset_materializations
    
  public.asset_observations:
    update_key: event_id
    meta:
      dagster: 
        asset_key: sling.cloud_product.asset_observations
    
  public.asset_partitions:
    meta:
      dagster: 
        asset_key: sling.cloud_product.asset_partitions
    
  public.alert_policies:
    meta:
      dagster: 
        asset_key: sling.cloud_product.alert_policies
