source: CLOUD_PRODUCTION_SHARD1
target: SLING_DB_SHARD1
defaults: 
  mode: incremental
  object: '{stream_table}'
  update_key: id

streams: 
  public.runs: 
    sql: >
      select *
      from public.runs
      where
        update_timestamp > coalesce({incremental_value}, to_timestamp(\'2021-06-30 00:0:00\', \'YYYY-MM-DD HH24:MI:SS\'))
        and update_timestamp <= coalesce({incremental_value}, to_timestamp(\'2021-06-30 00:0:00\', \'YYYY-MM-DD HH24:MI:SS\')) + INTERVAL \'1 hour\''
    primary_key: [id]
    update_key: update_timestamp
    meta:
      dagster:
        asset_key: sling.cloud_product_shard1.runs
