source: CLOUD_PRODUCTION_SHARD1
target: SLING_DB_SHARD1
defaults: 
  mode: incremental
  object: '{stream_table}'
  update_key: id

streams: 
  public.event_logs: 
    sql: >
      with candidates as (
        select * from public.event_logs where id > {incremental_value} and id <= {incremental_value} + 100000
      )
      select * from candidates where dagster_event_type is not null
    meta:
      dagster: 
        asset_key: sling.cloud_product_shard1.event_logs
