sources:
  github:
    repositories:
      dagster-io:
        - dagster
        - internal
        - community-integrations
        - dagster-website
        - elementl-website
      apache:
        - airflow
      PrefectHQ:
        - prefect
